### ISSUE TITLE
Use a sentence as input

### ISSUE THREAD

**Issue by GabrielLin** [allenai/citeomatic#96]
Hi, thank you for your great work. As mentioned in the paper, the input is the whole document, what about a sentence is given as the input? Is it OK? Thanks.

**Comment by sergeyf** [comment]
Hello. The input is a title and abstract. You can try a sentence but no guarantees. I recommend you use the follow-up model instead. SPECTER: https://github.com/allenai/specter

It's higher quality and easier to use. It even has an API.

**Comment by GabrielLin** [comment]
Got it. Thanks.
